cc_library(
  name = "bloom",
  hdrs = ["bloom.hpp"],
  copts = ['-std=c++14', '-O2'],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "hyperloglog",
  hdrs = ["hll.hpp"],
  copts = ['-std=c++14', '-O2'],
  visibility = ["//visibility:public"],
)