cc_test(
    name = "probabilistic",
    srcs = ["test_bloom.cpp"],
    copts = ["-std=c++14", "-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//probabilistic:bloom",
    ],
)